# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

median_cpp <- function(x) {
    .Call('_adept_median_cpp', PACKAGE = 'adept', x)
}

