# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convolveCpp <- function(a, b) {
    .Call('_adept_convolveCpp', PACKAGE = 'adept', a, b)
}

pmaxIdxCpp <- function(args) {
    .Call('_adept_pmaxIdxCpp', PACKAGE = 'adept', args)
}

slidingCorCpp <- function(shortvec, longvec, sd_shortvec) {
    .Call('_adept_slidingCorCpp', PACKAGE = 'adept', shortvec, longvec, sd_shortvec)
}

